[flavor]
use = "miasma"

[status]
sep_left = { open = "░▒▓", close = "▓▒░" }
sep_right = { open = "░▒▓", close = "▓▒░" }

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }
