mode = "auto"
vcs = "git"
line_numbers = true
wrap_lines = false

theme = "custom"

[custom_theme]
base = "graphite"
label = "Miasma"
background = "#222222"
panel = "#1c1c1c"
panelAlt = "#333333"
border = "#424134"
accent = "#c9a554"
accentMuted = "#333333"
text = "#d7c483"
muted = "#666666"
addedBg = "#253025"
removedBg = "#302520"
movedAddedBg = "#2f3025"
movedRemovedBg = "#2f3025"
contextBg = "#222222"
addedContentBg = "#2a3a2a"
removedContentBg = "#3a2a22"
contextContentBg = "#222222"
addedSignColor = "#5f875f"
removedSignColor = "#b36d43"
lineNumberBg = "#1c1c1c"
lineNumberFg = "#666666"
selectedHunk = "#333333"
badgeAdded = "#5f875f"
badgeRemoved = "#b36d43"
badgeNeutral = "#666666"
fileNew = "#5f875f"
fileDeleted = "#b36d43"
fileRenamed = "#78824b"
fileModified = "#c9a554"
fileUntracked = "#685742"
noteBorder = "#c9a554"
noteBackground = "#1c1c1c"
noteTitleBackground = "#333333"
noteTitleText = "#d7c483"

[custom_theme.syntax]
default = "#d7c483"
keyword = "#bb7744"
string = "#5f875f"
comment = "#666666"
number = "#bb7744"
function = "#78824b"
property = "#c9a554"
type = "#c9a554"
punctuation = "#c2c2b0"
operator = "#685742"
variable = "#d7c483"
